insert into categoria(nome, codigo) values("Geografia", "001");
insert into questao(descricao, categoria_id) values("Qual é o maior país do mundo em extensão territorial?",1);
insert into resposta(descricao, questao_id) values("Canadá",1);
insert into resposta(descricao, questao_id) values("China",1);
insert into resposta(descricao, certa, questao_id) values("Rússia",true,1);
insert into resposta(descricao, questao_id) values("Brasil",1);
insert into resposta(descricao, questao_id) values("Estados Unidos",1);


insert into questao(descricao, categoria_id) values("Qual é o rio mais extenso do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o menor continente do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o ponto mais alto do planeta?",1);
insert into questao(descricao, categoria_id) values("Quais são os dois países da América do Sul que não possuem fronteiras terrestres com o Brasil?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com maior número de habitantes no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o menor oceano do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual país tem a maior quantidade de ilhas no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país que possui a maior quantidade de fusos horários?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com o maior litoral do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o maior deserto do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é a cordilheira mais extensa do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com a maior biodiversidade do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com o maior número de vulcões ativos no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o maior delta do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é a capital mais alta do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país mais populoso da Europa?",1);
insert into questao(descricao, categoria_id) values("Qual é a língua mais falada no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o maior arquipélago do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com maior número de fronteiras no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o maior produtor de petróleo do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com o maior número de Patrimônios da Humanidade pela UNESCO?",1);
insert into questao(descricao, categoria_id) values("Qual é o maior lago de água doce do mundo em volume?",1);
insert into questao(descricao, categoria_id) values("Qual é o país mais extenso em ilhas no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é a ilha mais populosa do mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com maior percentual de sua área situada acima do Círculo Polar Ártico?",1);
insert into questao(descricao, categoria_id) values("Qual é a temperatura mais alta já registrada na Terra?",1);
insert into questao(descricao, categoria_id) values("Qual é o país com o maior número de rios em todo o mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é a cidade com maior número de arranha-céus no mundo?",1);
insert into questao(descricao, categoria_id) values("Qual é o país mais alto em relação ao nível do mar no mundo?",1);